import ButtonCreate from "@/app/(components)/all-campaigns/ButtonCreate";
import TabsView from "@/app/(components)/all-campaigns/TabsView";
import LeftLayout from "@/app/(components)/common/LeftLayout";
import Loading from "@/components/Loading";
import { MailCheck, MailOpen, Mails, SendHorizontal } from "lucide-react";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dummyData = [
    {
      queryString: "type",
      label: "All",
      link: "all",
      icon: <Mails size={20} />,
    },
    {
      queryString: "type",
      label: "Ongoing",
      link: "ongoing",
      icon: <SendHorizontal size={20} />,
    },
    {
      queryString: "type",
      label: "Draft",
      link: "draft",
      icon: <MailOpen size={20} />,
    },
    {
      queryString: "type",
      label: "Completed",
      link: "completed",
      icon: <MailCheck size={20} />,
    },
  ];
  return (
    <>
      <Suspense fallback={<Loading />}>
        <TabsView />
      </Suspense>
      <ButtonCreate />
      <div className="flex flex-col xl:flex-row gap-9 ml-4 pb-8">
        <LeftLayout dummyData={dummyData} />
        {children}
      </div>
    </>
  );
}
