import type { Metadata } from "next";
import "./globals.css";
import { Be_Vietnam_Pro } from "next/font/google";
import Sidebar from "@/app/(components)/Sidebar";
import Header from "@/app/(components)/Header";
import TanstackWrapper from "@/providers/tanstack.provider";
import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const beVietnam = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-bevietnam",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.22.4/css/grapes.min.css"
        />
      </head>
      <body className={` antialiased ${beVietnam.className}  `}>
        <TanstackWrapper>
          <div className="flex w-[100vw] min-xl:h-screen h-full bg-gray-100 ">
            <div className="max-xl:hidden">
              <Sidebar />
            </div>
            <main className="flex-1 pb-4">
              <Header />
              <div className=" px-8 bg-[#F4F7FE]">{children}</div>
              <Toaster />
            </main>
          </div>
        </TanstackWrapper>
      </body>
    </html>
  );
}
