import AudienceType from "@/app/(components)/audience/AudienceType";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex gap-9">
        <AudienceType />
        {children}
      </div>
    </>
  );
}
