import { TLayoutType } from "@/app/(components)/audience/LayoutType";
import LeftLayout from "@/app/(components)/common/LeftLayout";
import UsersIcon from "@/icon/UsersIcon";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dummyData: TLayoutType[] = [
    {
      queryString: "website",
      label: "All Audience",
      link: "",
      icon: <UsersIcon />,
    },
    {
      queryString: "website",
      label: "VIC Agency",
      link: "vic",
    },
    {
      queryString: "website",
      label: "VIC Agency",
      link: "/audience/all-audiences2",
    },
    {
      queryString: "website",
      label: "VIC Agency",
      link: "/audience/all-audiences2",
    },
    {
      queryString: "website",
      label: "VIC Agency",
      link: "/audience/all-audiences2",
    },
  ];
  return (
    <>
      <div className="flex flex-col xl:flex-row gap-9">
        <LeftLayout dummyData={dummyData} />
        {children}
      </div>
    </>
  );
}
